import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
//font chính
const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
});
// cho ví dụ code
const geistMono = Geist_Mono({
  variable: "--font-geistMono",
  subsets: ["latin"],
  display: "swap",
});

//font phụ
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "vietnamese"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="vi"
      className={`${geist.variable} ${geistMono.variable} ${inter.variable}  h-full antialiased`}
    >
      <body>{children}</body>
    </html>
  );
}
